# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Susanne Gov
email: susannegov@yahoo.com
description:
  '1609 Future Dr
  <br>Unit B
  <br>Austin, TX 78754'
baseurl: "/"
url: "/"
# the base hostname & protocol for your site, e.g. http://example.com
github_username: susannegov

# Build settings
theme: minima
remote_theme: minima
markdown: kramdown
show_excerpts: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed

header_pages:
  - projects.markdown
  - skills.markdown
  - resume.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
