# Welcome to Jekyll!

# Site settings
title: Susanne Gov - Portfolio
email: susannegov@yahoo.com
description: >- Personal portfolio website by Susanne Gov.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  susannegov

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
